---
- hosts: "{{aws_IP}}"
  become: true
  tasks:
    - name: create a directory for the ssh keys
      shell: su - postgres -c 'mkdir -p ~/.ssh'
        
    - name: Get the fingerprint of the key from postgres from azure_Instance
      shell: su - postgres -c 'ssh-keyscan -H {{azure_IP}} >> ~/.ssh/known_hosts'

    - name: Generate the key pair
      shell: su - postgres -c "ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''"

    - name: Copy the key to the azure_Instance
      shell: su - postgres -c 'sshpass -p 'postgres' ssh-copy-id postgres@{{azure_IP}}'

# Repeat for azure_Instance to aws_IP
- hosts: "{{azure_IP}}"
  become: true
  tasks:
    - name: create a directory for the ssh keys
      shell: su - postgres -c 'mkdir -p ~/.ssh'
        
    - name: Get the fingerprint of the key from postgres from azure_Instance
      shell: su - postgres -c 'ssh-keyscan -H {{aws_IP}} >> ~/.ssh/known_hosts'

    - name: Generate the key pair
      shell: su - postgres -c "ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''"

    - name: Copy the key to the azure_Instance
      shell: su - postgres -c 'sshpass -p 'postgres' ssh-copy-id postgres@{{aws_IP}}'
