---
- hosts: all
  become: true
  tasks:
    - name: Create the file repository configuration
      shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

    - name: Import the repository signing key
      shell: wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null

    - name: Update the package lists
      apt:
        update_cache: yes

    - name: Install the latest version of PostgreSQL
      apt:
        pkg:
          - postgresql
          - postgresql-client
        state: latest

    - name: Install and Enable the Citus extension
      shell: |
        curl https://install.citusdata.com/community/deb.sh > add-citus-repo.sh
        bash add-citus-repo.sh

    - name: Install the Citus extension
      apt:
        pkg:
          - postgresql-15-citus-11.1
        state: latest

    - name: Preload citus extension
      shell: |
        pg_conftool 15 main set shared_preload_libraries citus
        systemctl restart postgresql
        pg_conftool 15 main set listen_addresses '*'

    - name: Restart the PostgreSQL service
      service:
        name: postgresql
        state: restarted

    - name: Make sure it starts on boot
      shell: update-rc.d postgresql enable

    - name: Add the citus extension to the postgres database
      shell: |
        sudo -i -u postgres psql -c "CREATE EXTENSION citus;"
        sudo mkdir -p /logs/archive
        sudo chown postgres:postgres -R /logs/

- hosts: "{{aws_IP}}"
  become: true
  tasks:
    - name: Configure the IP address(es) listen to for connections from clients in postgresql.conf by removing '#'in front of listen_address and give *. Which means listen connections from all.
      shell: |
        sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/15/main/postgresql.conf
        sed  -i "s/#archive_mode = off/archive_mode = on/g" /etc/postgresql/15/main/postgresql.conf
        sed  -i "s/#archive_command = ''/archive_command = 'cp %p \/logs\/archive\/%f'/g" /etc/postgresql/15/main/postgresql.conf

    - name: connect to PostgreSQL on master server and create replica login.
      shell: |
        sudo -i -u postgres psql -c "CREATE USER {{rep_user}} WITH REPLICATION PASSWORD '{{rep_user_password}}';"

    - name: Enter the following entry pg_hba.conf file which is located in
      shell: |
        echo "host    replication     {{rep_user}}      {{azure_IP}}/32         md5" >> /etc/postgresql/15/main/pg_hba.conf

    - name: Enter the following entry pg_hba.conf file which is located in
      shell: |
        echo "host    all             all               {{aws_IP_haproxy}}/32         trust" >> /etc/postgresql/15/main/pg_hba.conf

    - name: Restart the PostgreSQL service
      service:
        name: postgresql
        state: restarted

- hosts: "{{azure_IP}}"
  become: true
  tasks:
    - name: Stop PostgreSQL on Slave server
      service:
        name: postgresql
        state: stopped

    - name: Copy the content of the slave main to main_old
      shell: |
        sudo -i -u postgres cp -R /var/lib/postgresql/15/main /var/lib/postgresql/15/main_old
    - name: Remove the content of the slave main
      shell: |
        sudo -i -u postgres rm -rf /var/lib/postgresql/15/main/

    - name: Now, use basebackup to take the base backup with the right ownership with postgres(or any user with right permissions).
      expect:
        command: sudo -i -u postgres pg_basebackup -h {{aws_IP}} -D /var/lib/postgresql/15/main -U {{rep_user}} -P -v -R -X stream -C -S slaveslot
        responses:
          "Password:": "{{rep_user_password}}"

    - name: Check if standby.signal file is created in the main directory
      shell: |
        sudo -i -u postgres ls -ltrh /var/lib/postgresql/15/main/
      register: standby_signal

    - name: Display the output
      debug:
        msg: "{{standby_signal.stdout}}"

    - name: Start PostgreSQL on Slave server
      service:
        name: postgresql
        state: started

    - name: Configure the IP address(es) listen to for connections from clients in postgresql.conf by removing '#'in front of listen_address and give *. Which means listen connections from all.
      shell: |
        sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/15/main/postgresql.conf

    - name: Enter the following entry pg_hba.conf file which is located in
      shell: |
        echo "host    all             all               {{aws_IP_haproxy}}/32         trust" >> /etc/postgresql/15/main/pg_hba.conf

    - name: Restart the PostgreSQL service
      service:
        name: postgresql
        state: restarted

- hosts: "{{aws_IP_haproxy}}"
  become: true
  tasks:
    - name: Update the package lists
      apt:
        update_cache: yes

    - name: Install the latest version of HAProxy
      apt:
        pkg:
          - haproxy
        state: latest

    - name: Delete all the content of the haproxy.cfg file
      shell: |
        echo "" > /etc/haproxy/haproxy.cfg

    - name: Add this content to the haproxy.cfg file
      shell: |
        echo "global
                  maxconn 100

              defaults
                  log global
                  mode tcp
                  retries 2
                  timeout client 30m
                  timeout connect 4s
                  timeout server 30m
                  timeout check 5s

                listen stats
                    mode http
                    bind *:7000
                    stats enable
                    stats uri /

                listen PostgreSQL
                    bind *:5000
                    option pgsql-check user postgres
                    default-server inter 3s fall 3
                    server {{aws_IP}} {{aws_IP}}:5432 check port 5432
                    server {{azure_IP}} {{azure_IP}}:5432 check port 5432" >> /etc/haproxy/haproxy.cfg

    - name: Start the HAProxy service
      service:
        name: haproxy
        state: started

    - name: Enable the HAProxy service
      service:
        name: haproxy
        enabled: yes

    - name: Restart the HAProxy service
      service:
        name: haproxy
        state: restarted
